# Generated by Django 5.1.7 on 2025-04-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockeDis', models.IntegerField()),
                ('image', models.ImageField(upload_to='img')),
                ('category', models.CharField(blank=True, choices=[('Teint', 'Teint'), ('Yeux', 'Yeux'), ('Levres', 'Lèvres'), ('Pinceaux', 'Pinceaux et éponges')], max_length=15, null=True)),
                ('estDis', models.BooleanField(default=True)),
            ],
        ),
    ]
